version: '3'
services:
  frontend:
    image: ghcr.io/vddewolf/cusmatomatic-frontend:latest
    container_name: cusmatomatic-frontend
    hostname: cusmatomatic-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - cusmatomatic
    environment:
      - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    restart: unless-stopped
    depends_on:
      - backend
  backend:
    image: ghcr.io/vddewolf/cusmatomatic-backend:latest
    container_name: cusmatomatic-backend
    hostname: ${BACKEND_HOSTNAME}
    ports:
      - "${BACKEND_PORT}:5001"
    networks:
      - cusmatomatic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CUSMATOMATIC_APP_HOTLOAD_LOCATION}:/cusmatomatic-apps:z
      - ${CUSMATOMATIC_FILE_LOCATION}:/cusmatomatic-files:z
    env_file: .env
    environment:
      - CUSMATOMATIC_APP_HOTLOAD_FOLDER=/cusmatomatic-apps
      - CUSMATOMATIC_FILE_LOCATION=/cusmatomatic-files
    restart: unless-stopped
  orborus:
    image: ghcr.io/vddewolf/cusmatomatic-orborus:latest
    container_name: cusmatomatic-orborus
    hostname: cusmatomatic-orborus
    networks:
      - cusmatomatic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CUSMATOMATIC_APP_SDK_TIMEOUT=300
      - CUSMATOMATIC_ORBORUS_EXECUTION_CONCURRENCY=7
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:5001
      - DOCKER_API_VERSION=1.40
      - CUSMATOMATIC_BASE_IMAGE_NAME=${CUSMATOMATIC_BASE_IMAGE_NAME}
      - CUSMATOMATIC_BASE_IMAGE_REGISTRY=${CUSMATOMATIC_BASE_IMAGE_REGISTRY}
      - CUSMATOMATIC_BASE_IMAGE_TAG_SUFFIX=${CUSMATOMATIC_BASE_IMAGE_TAG_SUFFIX}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - CUSMATOMATIC_PASS_WORKER_PROXY=${CUSMATOMATIC_PASS_WORKER_PROXY}
      - CUSMATOMATIC_PASS_APP_PROXY=${CUSMATOMATIC_PASS_APP_PROXY}
      - CUSMATOMATIC_STATS_DISABLED=true
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
  opensearch:
    image: ghcr.io/vddewolf/cusmatomatic-opensearch:2.14.0
    hostname: cusmatomatic-opensearch
    container_name: cusmatomatic-opensearch
    env_file: .env
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - bootstrap.memory_lock=true
      - DISABLE_PERFORMANCE_ANALYZER_AGENT_CLI=true
      - cluster.initial_master_nodes=cusmatomatic-opensearch
      - cluster.routing.allocation.disk.threshold_enabled=false
      - cluster.name=cusmatomatic-cluster
      - node.name=cusmatomatic-opensearch
      - node.store.allow_mmap=false
      - discovery.seed_hosts=cusmatomatic-opensearch
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${CUSMATOMATIC_OPENSEARCH_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - ${DB_LOCATION}:/usr/share/opensearch/data:z
    ports:
      - 9200:9200
    networks:
      - cusmatomatic
    restart: unless-stopped
networks:
  cusmatomatic:
    driver: bridge
